#include "ytdl/CommandBuilder.h"

#include <stdexcept>

namespace ytdlnis::ytdl {

std::vector<std::wstring> CommandBuilder::build(const YtdlRequest& request,
                                                const RuntimePaths& runtime) {
    if (runtime.ytDlp.empty()) throw std::invalid_argument("yt-dlp path is required");
    if (request.url.empty()) throw std::invalid_argument("URL is required");

    std::vector<std::wstring> args;
    args.reserve(40 + request.extraArguments.size());

    args.emplace_back(L"--no-color");
    args.emplace_back(L"--newline");
    args.emplace_back(L"--progress");

    if (!runtime.ffmpeg.empty()) {
        args.emplace_back(L"--ffmpeg-location");
        args.push_back(runtime.ffmpeg.parent_path().wstring());
    }

    if (!request.playlist) args.emplace_back(L"--no-playlist");

    switch (request.type) {
    case DownloadType::Audio:
        args.emplace_back(L"--extract-audio");
        if (request.audio.container) {
            args.emplace_back(L"--audio-format");
            args.push_back(*request.audio.container);
        }
        if (request.audio.quality) {
            args.emplace_back(L"--audio-quality");
            args.push_back(std::to_wstring(*request.audio.quality));
        }
        if (request.audio.codec) {
            args.emplace_back(L"--postprocessor-args");
            args.push_back(L"ExtractAudio:-c:a " + *request.audio.codec);
        }
        break;
    case DownloadType::Data:
        args.emplace_back(L"--dump-single-json");
        args.emplace_back(L"--skip-download");
        break;
    case DownloadType::Custom:
    case DownloadType::Video:
        if (request.video.height) {
            args.emplace_back(L"--format");
            args.push_back(L"bestvideo[height<=" + std::to_wstring(*request.video.height) + L"]+bestaudio/best");
        }
        break;
    }

    if (request.format) {
        args.emplace_back(L"--format");
        args.push_back(*request.format);
    }

    if (!request.output.directory.empty()) {
        args.emplace_back(L"--paths");
        args.push_back(request.output.directory.wstring());
    }

    if (!request.output.filenameTemplate.empty()) {
        args.emplace_back(L"--output");
        args.push_back(request.output.filenameTemplate);
    }

    if (request.output.embedMetadata) args.emplace_back(L"--embed-metadata");
    if (request.output.embedThumbnail) args.emplace_back(L"--embed-thumbnail");

    if (request.subtitles.enabled) {
        args.emplace_back(L"--write-subs");
        if (request.subtitles.autoGenerated) args.emplace_back(L"--write-auto-subs");
        if (!request.subtitles.languages.empty()) {
            args.emplace_back(L"--sub-langs");
            std::wstring languages;
            for (std::size_t i = 0; i < request.subtitles.languages.size(); ++i) {
                if (i) languages += L',';
                languages += request.subtitles.languages[i];
            }
            args.push_back(std::move(languages));
        }
        if (request.subtitles.embed) args.emplace_back(L"--embed-subs");
        if (request.subtitles.convertToVtt) {
            args.emplace_back(L"--convert-subs");
            args.emplace_back(L"vtt");
        }
    }

    if (request.cookieFile) {
        args.emplace_back(L"--cookies");
        args.push_back(request.cookieFile->wstring());
    }

    if (request.proxy) {
        args.emplace_back(L"--proxy");
        args.push_back(*request.proxy);
    }

    for (const auto& header : request.headers) {
        args.emplace_back(L"--add-header");
        args.push_back(header);
    }

    if (request.downloadSections) {
        args.emplace_back(L"--download-sections");
        args.push_back(*request.downloadSections);
    }

    for (const auto& extra : request.extraArguments) args.push_back(extra);
    args.push_back(request.url);
    return args;
}

} // namespace ytdlnis::ytdl
