#pragma once

#include <cstdint>
#include <filesystem>
#include <optional>
#include <string>
#include <vector>

namespace ytdlnis::ytdl {

enum class DownloadType {
    Video,
    Audio,
    Data,
    Custom
};

enum class DownloadStatus {
    Active,
    Paused,
    Queued,
    Error,
    Cancelled,
    Saved,
    Processing,
    Scheduled,
    Duplicate
};

struct AudioPreferences {
    std::optional<std::wstring> codec;
    std::optional<int> quality;
    std::optional<std::wstring> container;
};

struct VideoPreferences {
    std::optional<std::wstring> codec;
    std::optional<int> height;
    std::optional<int> fps;
    std::optional<std::wstring> container;
};

struct SubtitlePreferences {
    bool enabled = false;
    bool autoGenerated = false;
    std::vector<std::wstring> languages;
    bool embed = false;
    bool convertToVtt = false;
};

struct OutputOptions {
    std::filesystem::path directory;
    std::wstring filenameTemplate;
    bool embedMetadata = false;
    bool embedThumbnail = false;
};

struct YtdlRequest {
    std::wstring url;
    DownloadType type = DownloadType::Video;
    std::optional<std::wstring> format;
    AudioPreferences audio;
    VideoPreferences video;
    SubtitlePreferences subtitles;
    OutputOptions output;
    std::vector<std::wstring> extraArguments;
    std::optional<std::filesystem::path> cookieFile;
    std::optional<std::wstring> proxy;
    std::vector<std::wstring> headers;
    std::optional<std::wstring> downloadSections;
    bool playlist = true;
};

} // namespace ytdlnis::ytdl
